### ISSUE TITLE
Window resizing – Help section

### ISSUE THREAD

**Issue by Ricky-Tigg** [F1ash/dnscrypt-proxy-gui#10]
Hello F1ash. Since the version 1.11.11-1 release date, in Red Hat Bugzilla, issue [1537159](https://bugzilla.redhat.com/show_bug.cgi?id=1537159) is no longer active and as a result the use of that piece of software could be enjoyed. Its interface is intuitive, and there is no reasonable motive to require a major change related to it.

However the restriction regarding the maximal allowed dimensions of the interface window does not seem absolutely required for a good use of the application, as indeed its whole settings list is short enough to be displayed comfortably as a one sight-view under the vertical axis,

In that context, would it be possible to envisage not to restrict the window dimensions, at least not so tightly, and even less regarding the dimension under the vertical axis? Such enhancement would be beneficent not only to the Application Settings view but also its effect would be most noticeable while using the Restore System DNS Resolver Settings view, which may contain a list of settings long enough so that it would be best for it to be displayed under a lager dimensions set than the actual one enabled by default.

Otherwise the application may lack a succinct Help section for users be they beginners or experimented ones. There is no mention of the meaning of the icon located in some case in front of the name of a server in the main view. On a small enough laptop screen with default resolution, the details regarding the icon itself cannot be perceived. Regards.

**Comment by F1ash** [comment]
> Since the version 1.11.11-1 release date, in Red Hat Bugzilla, issue 1537159 is no longer active and as a result the use of that piece of software could be enjoyed.

if bug is inactive then you can to close it :)

**Comment by Ricky-Tigg** [comment]
Red Hat Bugzilla – Bug 1537159
Status: NEW → CLOSED
Resolution: --- → CURRENTRELEASE
Last Closed: 2018-02-20 08:17:51
