### ISSUE TITLE
Enhancement request regarding filters and options related to security

### ISSUE THREAD

**Issue by Ricky-Tigg** [F1ash/dnscrypt-proxy-gui#13]

**Comment by F1ash** [comment]
![image](https://user-images.githubusercontent.com/499075/36897851-52244810-1e29-11e8-867e-9c6fb5ddb801.png)
At this time you can to enable or disable servers manually... 

But i will try to implement your requests as possible.

**Comment by Ricky-Tigg** [comment]
Server responds test has significant role in the task of selecting the appropriate DNS resolver from a user's perspective. Nevertheless since the final output related to that test is non-existent, its interest is unnoticed. In that context, would it be reasonable to expect the results related to the responds time to deserve to be gathered in a final report. Such report would not need to be as much extended an polished as those provided by tools DNS Benchmark (DOS/Windows program which works in Linux using an Windows API emulator) and Namebench.
