### ISSUE TITLE
Application cannot be launched under Fedora

### ISSUE THREAD

**Issue by Ricky-Tigg** [F1ash/dnscrypt-proxy-gui#16]
Application cannot be launched. The following commands were executed on _Gnome_ version 3.32.2:
- Under _Wayland_ server:

Same results using `DNSCryptClient` or `/usr/bin/DNSCryptClient`.
```
$ DNSCryptClient
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

$ sudo ps -aux | grep -i dnscrypt
root      2806  1.0  0.5 505628 21300 ?        Ssl  14:37   0:00 /usr/libexec/kf5/kauth/dnscrypt_client_test_helper

$ QT_QPA_PLATFORM=wayland DNSCryptClient
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread

$ sudo DNSCryptClient
No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

$ sudo QT_QPA_PLATFORM=wayland DNSCryptClient
error: XDG_RUNTIME_DIR not set in the environment.
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" (...)
```
- Under _X_ server:

No message produced when executing `DNSCryptClient`
```
$ sudo DNSCryptClient
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
```
Additional information: _dnscrypt-proxy_ was installed as dependency along with installation of _dnscrypt-proxy-gui_. System was rebooted.
```
$ dnf list installed | grep -i dnscrypt
dnscrypt-proxy.x86_64                 2.0.23-1.fc30               @updates        
dnscrypt-proxy-gui.x86_64             1.21.16-4.fc30              @updates
$ rpm -ql dnscrypt-proxy-gui | grep '^/usr/bin'
/usr/bin/DNSCryptClient
# systemctl list-unit-files | grep -i dnscrypt | sort
DNSCryptClient@.service                      static
DNSCryptClient_test@.service                 static
DNSCryptClient_test_v2.service               static
dnscrypt-proxy.service                       disabled
dnscrypt-proxy.socket                        disabled
```

**Comment by F1ash** [comment]
i'm not use Wayland yet... Maybe need to use `xorg-x11-server-Xwayland.x86_64 : Wayland X Server` for according X11-application with Wayland

**Comment by Ricky-Tigg** [comment]
Checking that suggested package is required by _dnscrypt-proxy-gui_.; output indicates that it is not:
```
$ LANG=C dnf repoquery --requires xorg-x11-server-Xwayland --recursive --resolve | grep ^dnscrypt-proxy-gui
Last metadata expiration check: 4:48:50 ago on Thu Jun 20 15:11:14 2019.
```
It was installed while executions of commands i reported took place:
```
$ dnf list installed | grep -i xorg-x11-server-Xwayland
xorg-x11-server-Xwayland.x86_64           1.20.4-3.fc30           @anaconda
```

**Comment by F1ash** [comment]
maybe some bug with Qt private_API because include dirs for it is
DBusPrivDirs: /usr/include/qt5/QtDBus/5.12.3;/usr/include/qt5/QtDBus/5.12.3/QtDBus;/usr/include/qt5/QtCore/5.12.3;/usr/include/qt5/QtCore/5.12.3/QtCore

but they are empty in my rawhide... So maybe some bug in building ...

**Comment by Nokia808** [comment]
Hi. I'm also suffer from this issue ! Please look to this bug oopened by me on RedHat Bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=1720793

It seem that certain Fedora users suffer from this issue while other are not !

**Comment by Ricky-Tigg** [comment]
Time to close –my report–. In kernel v. 5.3.15-300, dnscrypt-proxy-gui v. 1.21.16, currently wrapping dnscrypt-proxy v. 2.0.34-1, does launch as intended. F1ash, merry Christmas.

**Comment by Ricky-Tigg** [comment]
Time to reopen. System rebooted. Issue alive.  Under Wayland, output from `strace DNSCryptClient 2>DNSCryptClient.txt`: 
[DNSCryptClient.txt](https://github.com/F1ash/dnscrypt-proxy-gui/files/3965028/DNSCryptClient.txt)

**Comment by Ricky-Tigg** [comment]
Hi F1ash. I have to assume that no investigation from your part has been conducted yet.. II kept on testing this application with new releases from @jedisct1 of dnscrypt-proxy.
```
$ dnf list installed dnscrypt* | sed 1d
dnscrypt-proxy.x86_64                  2.0.44-1.fc32               @updates
dnscrypt-proxy-gui.x86_64              1.21.16-11.fc32             @updates
```
That logs file is empty
```
# ls -l /var/log/ | grep 'dnscrypt-proxy'
lrwxrwxrwx. 1 root   root  22  9. 9. 15:48 dnscrypt-proxy -> private/dnscrypt-proxy
```
Output resulting from `journalctl -f` on Wayland: [Journalctl_DNSCryptClient_1.21.16.txt](https://github.com/F1ash/dnscrypt-proxy-gui/files/5195956/Journalctl_DNSCryptClient_1.21.16.txt)
