### ISSUE TITLE
config window not themeable

### ISSUE THREAD

**Issue by omni6** [F1ash/dnscrypt-proxy-gui#2]
Your gui is a very handy app, expecially for not so advanced users. But what bothers me is that it is hard readable and that the app don't saves the window properties (width/height). Indeed its written in qt why its not themeable?
Can we expect improvements for this?

[Screenshot](http://imgur.com/a/vIblw)

**Comment by F1ash** [comment]
there is used custom style for widgets... ok, will be common for DE.

**Comment by omni6** [comment]
in any case 2 packages from plasma are needed. isnt this software designed for plasma? yes interesting for lxqt too... but if you make little improvements its a perfect kde app.

**Comment by F1ash** [comment]
KAuth and KNotifications not from Plasma... Now KDE Framework (5) more flexible, therefore kauth, knotification, plasma are different modules of KF5. Anymore, this app is oriented for qt-based DE.
I have not time for maintain two different packages with same functionality.

**Comment by F1ash** [comment]
_...that the app don't saves the window properties (width/height)_
Strange, inFedora -- saved\restored geometry.

**Comment by F1ash** [comment]
_it is hard readable..._
what you means? Can write some detailed?

**Comment by omni6** [comment]
> KAuth and KNotifications not from Plasma... Now KDE Framework (5) more flexible, therefore kauth, knotification, plasma are different modules of KF5. Anymore, this app is oriented for qt-based DE.
> I have not time for maintain two different packages with same functionality.

yes i know they are frameworks packets not plasma. 
you mean KAuth and kauth are two different packages? because in arch there is just one package and this is only [kauth](https://www.archlinux.org/packages/extra/x86_64/kauth/) . Maybe in fedora different. Anyway it should just respect my theme and i think this is a qt thing, not related to DE.

If you look the screenshot you can see why its bad readable. the contrast of the text and the background. light grey on white....

**Comment by F1ash** [comment]
> the contrast of the text and the background. light grey on white....

Now clear... i will remove custom steelSheets and then app will inherit style of DE.

> you mean KAuth and kauth are two different packages?

No, not about...
I wanted to say that I purposely used part of the KF5 for my application, because it does not have the Plasma and many other parts in the dependencies - both in KF5 modules, and packages in distributions, and KF5 modules more comfortable for using than their qt-parents.

**Comment by omni6** [comment]
all will be good :)

**Comment by F1ash** [comment]
> I have not time for maintain two different packages with same functionality.

If make app for KDE, then need make for qt-based DE too. It will be two different codes and packages... I have not time for it. I hope now I answered on all the questions.

**Comment by omni6** [comment]
hmm, this i dont understand. the app is for qt und builds just fine using cmake on arch. runs flawless on kde, the only thing what is annoying is that it is not themeable. there is nothing else to change with the packages. perhaps i am not advanced enough to understand ;). 
anyway if you are interesting to feature complete this gui i would have another request: 

option to change port of dnscrypt-proxy in your settings window.

reason:
on my system dnscrypt proxy use port 5353. to serve dns requests to [pdnsd](https://wiki.archlinux.org/index.php/Pdnsd) what is my first instance for dns lookup. so pdnsd have to use port 53.

**Comment by F1ash** [comment]
> option to change port of dnscrypt-proxy in your settings window.

Ok. Now app uses 53&5353 ports for get DNS requests and testing the responds from DNS servers.
I will implement settings for each procedure.

**Comment by omni6** [comment]
great!

**Comment by omni6** [comment]
very nice !!!

![screenshot_20170520_182948](https://cloud.githubusercontent.com/assets/24492439/26277566/7921dce6-3d8a-11e7-93be-00efc2696765.png)

**Comment by F1ash** [comment]
That is not all. Now you can change ports for job and testing responds. But new version not released, because yet need to implement check and change used ports at start. Because after update application from repository systemd units will contains default ports.

**Comment by omni6** [comment]
doesnt work!
`ExecStart=/usr/sbin/dnscrypt-proxy -a 127.0.0.1:5353 -R %i
`
to change ports dnscrypt-proxy.socket must be changed
i guess this isnt possible?

look here: [Arch Wiki](https://wiki.archlinux.org/index.php/DNSCrypt#Change_port)


just for interest, for what is port for testing server responds used?

**Comment by F1ash** [comment]
port for testing server responds  is 53535 by application default, but that port can be any for usage.
