### ISSUE TITLE
change ports doesn't work

### ISSUE THREAD

**Issue by omni6** [F1ash/dnscrypt-proxy-gui#4]
> That is not all. Now you can change ports for job and testing responds. But new version not released, because yet need to implement check and change used ports at start. Because after update application from repository systemd units will contains default ports.

**ExecStart=/usr/sbin/dnscrypt-proxy -a 127.0.0.1:5353 -R %i**
doesnt work! to change ports dnscrypt-proxy.socket must be changed...

look here: [Arch Wiki](https://wiki.archlinux.org/index.php/DNSCrypt#Change_port)

just for interest, for what is port for testing server responds used?

**Comment by F1ash** [comment]
> just for interest, for what is port for testing server responds used?

port for testing server responds is 53535 by application default, but that port can 
be any for usage.

> to change ports dnscrypt-proxy.socket must be changed...

`# rpm -q --filesbypkg dnscrypt-proxy`
dnscrypt-proxy            /etc/dnscrypt-proxy.conf
dnscrypt-proxy            /etc/dnscrypt-proxy.conf.example
dnscrypt-proxy            /usr/bin/hostip
dnscrypt-proxy            /usr/include/dnscrypt
dnscrypt-proxy            /usr/include/dnscrypt/plugin.h
dnscrypt-proxy            /usr/include/dnscrypt/private.h
dnscrypt-proxy            /usr/include/dnscrypt/version.h
dnscrypt-proxy            /usr/lib64/dnscrypt-proxy
dnscrypt-proxy            /usr/lib64/dnscrypt-proxy/libdcplugin_example.la
dnscrypt-proxy            /usr/lib64/dnscrypt-proxy/libdcplugin_example.so
dnscrypt-proxy            /usr/lib64/dnscrypt-proxy/libdcplugin_example_cache.la
dnscrypt-proxy            /usr/lib64/dnscrypt-proxy/libdcplugin_example_cache.so
dnscrypt-proxy            /usr/lib64/dnscrypt-proxy/libdcplugin_example_logging.la
dnscrypt-proxy            /usr/lib64/dnscrypt-proxy/libdcplugin_example_logging.so
dnscrypt-proxy            /usr/sbin/dnscrypt-proxy
dnscrypt-proxy            /usr/share/dnscrypt-proxy
dnscrypt-proxy            /usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv
dnscrypt-proxy            /usr/share/dnscrypt-proxy/minisign.pub
dnscrypt-proxy            /usr/share/man/man8/dnscrypt-proxy.8.gz
dnscrypt-proxy            /usr/share/man/man8/hostip.8.gz

in Fedora that socket is absent.

**Comment by F1ash** [comment]
i wrote to [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1452995)... Maybe it will be solved soon.

**Comment by jedisct1** [comment]
In order to be compatible with more distributions, and possibly with BSD systems, maybe don't require `dnscrypt-proxy.socket` at all? The [static binaries](https://github.com/jedisct1/dnscrypt-proxy-installer) don't include support for systemd sockets.

If available, systemd can still be used to spawn the service, but systemd is not required to listen to UDP and TCP ports.

**Comment by F1ash** [comment]
not clear... in fedora without systemd units in dnscrypt-proxy package all works right -- if i change "job" port then dnscrypt-proxy get DNS data, but application not get it (because uses 53 port by default). And that are works without dnscrypt-proxy.socket. If need change the some ports , then application cannot check all variants.

**Comment by omni6** [comment]
ha lol,
edited the `DNSCryptClient@.service` 
ExecStart=/usr/sbin/dnscrypt-proxy -a 127.0.0.1:5353 `-u dnscrypt` -R %i

everything works now. look here:
arch (just my?) file permissions for var:
```
rwxr-xr-x  3 root root     4096 10.03.2017 17:10 db/
drwx------  2 root dnscrypt 4096 21.02.2017 20:21 dnscrypt/
drwxr-xr-x  2 root root     4096 30.09.2015 21:17 empty/
```

if dnscrypt is executed from the gui it needs also set to user `dnscrypt` 
portchanging is now working.

can you implement` run as user` option? i think this will do the trick...

**Comment by F1ash** [comment]
Why 'dnscrypt' ? Maybe a current session user?

**Comment by omni6** [comment]
yeh at installation i followed recommended instructions in arch wiki. 
[dnscrypt runs with root privileges](https://wiki.archlinux.org/index.php/DNSCrypt#dnscrypt_runs_with_root_privileges)

**Comment by omni6** [comment]
for security reasons own user/group

**Comment by F1ash** [comment]
hmmm... ok, i will try, but only as optional parameter.

**Comment by F1ash** [comment]
fixed.

**Comment by omni6** [comment]
yep, fantastic!
