### ISSUE TITLE
don't build

### ISSUE THREAD

**Issue by SergeyDjam** [F1ash/dnscrypt-proxy-gui#5]
Hello, i build version dnscrypt-proxy-gui-1.9.8
`cmake .`
`make`
build faild

> Scanning dependencies of target DNSCryptClient
> [ 25%] Building CXX object src/CMakeFiles/DNSCryptClient.dir/main.cpp.o
> In file included from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/mainwindow.h:10:0,
>                  from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/main.cpp:2:
> /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/server_panel.h:16:44: ошибка: нет декларации «nullptr» в этой области видимости
>      explicit ServerPanel(QWidget *parent = nullptr);
>                                             ^
> In file included from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/mainwindow.h:11:0,
>                  from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/main.cpp:2:
> /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/button_panel.h:13:44: ошибка: нет декларации «nullptr» в этой области видимости
>      explicit ButtonPanel(QWidget *parent = nullptr);
>                                             ^
> In file included from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/mainwindow.h:12:0,
>                  from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/main.cpp:2:
> /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/info_panel.h:20:32: предупреждение: non-static data member initializers only available with -std=c++11 or -std=gnu++11
>      int              timerId = 0;
>                                 ^
> /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/info_panel.h:15:42: ошибка: нет декларации «nullptr» в этой области видимости
>      explicit InfoPanel(QWidget *parent = nullptr);
>                                           ^
> In file included from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/test_respond.h:7:0,
>                  from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/mainwindow.h:13,
>                  from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/main.cpp:2:
> /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/test_widget.h:16:43: ошибка: нет декларации «nullptr» в этой области видимости
>      explicit TestWidget(QWidget *parent = nullptr);
>                                            ^
> In file included from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/mainwindow.h:13:0,
>                  from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/main.cpp:2:
> /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/test_respond.h:13:44: ошибка: нет декларации «nullptr» в этой области видимости
>      explicit TestRespond(QWidget *parent = nullptr);
>                                             ^
> In file included from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/app_settings.h:10:0,
>                  from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/mainwindow.h:14,
>                  from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/main.cpp:2:
> /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/port_settings.h:12:45: ошибка: нет декларации «nullptr» в этой области видимости
>      explicit PortSettings(QWidget *parent = nullptr,
>                                              ^
> In file included from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/mainwindow.h:14:0,
>                  from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/main.cpp:2:
> /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/app_settings.h:22:44: ошибка: нет декларации «nullptr» в этой области видимости
>      explicit AppSettings(QWidget *parent = nullptr);
>                                             ^
> In file included from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/mainwindow.h:15:0,
>                  from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/main.cpp:2:
> /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/tray/traywidget.h:13:39: ошибка: нет декларации «nullptr» в этой области видимости
>    explicit TrayIcon(QWidget *parent = nullptr);
>                                        ^
> In file included from /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/main.cpp:2:0:
> /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/mainwindow.h:21:43: ошибка: нет декларации «nullptr» в этой области видимости
>      explicit MainWindow(QWidget *parent = nullptr);
>                                            ^
> /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/main.cpp: В функции «int main(int, char**)»:
> /home/admin/rpmbuild/BUILD/dnscrypt-proxy-gui-1.9.8/src/main.cpp:11:16: ошибка: call to «MainWindow::MainWindow(QWidget*)» uses the default argument for parameter 1, which is not yet defined
>      MainWindow w;
>                 ^
> make[2]: *** [src/CMakeFiles/DNSCryptClient.dir/build.make:143: src/CMakeFiles/DNSCryptClient.dir/main.cpp.o] Ошибка 1
> make[1]: *** [CMakeFiles/Makefile2:88: src/CMakeFiles/DNSCryptClient.dir/all] Ошибка 2
> make: *** [Makefile:128: all] Ошибка 2

diagnostic:
OS: ROSA Desktop Fresh R8.1 release 2014.1 for x86_64
Kernel: Linux nb 4.9.20-nrj-desktop-1rosa-x86_64 #1 SMP PREEMPT Sat Apr 1 22:43:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Qt5: 5.6.1
cmake version 3.5.2
gcc (Linaro GCC 4.9-2014.08) 4.9.2 20140811 (ROSA)
rpm -qa | grep kf5
lib64kf5js5-5.24.0-1-rosa2014.1.x86_64
lib64kf5solid5-5.24.0-1-rosa2014.1.x86_64
lib64kf5solid-qml-5.24.0-1-rosa2014.1.x86_64
lib64kf5itemviews5-5.24.0-1-rosa2014.1.x86_64
lib64kf5dnssd5-5.24.0-1-rosa2014.1.x86_64
lib64kf5i18n5-5.24.0-1-rosa2014.1.x86_64
kdnssd-kf5-i18n-5.24.0-1-rosa2014.1.noarch
lib64kf5archive5-5.24.0-1-rosa2014.1.x86_64
lib64kf5configcore5-5.24.0-1-rosa2014.1.x86_64
lib64kf5coreaddons5-5.24.0-1-rosa2014.1.x86_64
lib64kf5configgui5-5.24.0-1-rosa2014.1.x86_64
lib64kf5auth5-5.24.0-1-rosa2014.1.x86_64
lib64kf5codecs5-5.24.0-1-rosa2014.1.x86_64
lib64kf5guiaddons5-5.24.0-1-rosa2014.1.x86_64
lib64kf5widgetsaddons5-5.24.0-1-rosa2014.1.x86_64
lib64kf5configwidgets5-5.24.0-1-rosa2014.1.x86_64
lib64kf5completion5-5.24.0-1-rosa2014.1.x86_64
lib64kf5windowsystem5-5.24.0-1-rosa2014.1.x86_64
lib64kf5dbusaddons5-5.24.0-1-rosa2014.1.x86_64
lib64kf5crash5-5.24.0-1-rosa2014.1.x86_64
lib64kf5globalaccel5-5.24.0-1-rosa2014.1.x86_64
lib64kf5iconthemes5-5.24.0-1-rosa2014.1.x86_64
lib64kf5attica5-5.24.0-1-rosa2014.1.x86_64
lib64kf5globalaccelprivate5-5.24.0-1-rosa2014.1.x86_64
lib64kf5sonnetcore5-5.24.0-1-rosa2014.1.x86_64
lib64kf5service5-5.24.0-1-rosa2014.1.x86_64
lib64kf5sonnetui5-5.24.0-1-rosa2014.1.x86_64
lib64kf5textwidgets5-5.24.0-1-rosa2014.1.x86_64
kwallet-kf5-i18n-5.24.0-1-rosa2014.1.noarch
lib64kf5kiontlm5-5.24.0-1-rosa2014.1.x86_64
lib64kf5xmlgui5-5.24.0-1-rosa2014.1.x86_64
lib64kf5wallet5-5.24.0-1-rosa2014.1.x86_64
lib64kf5kiocore5-5.24.0-1-rosa2014.1.x86_64
lib64kf5jobwidgets5-5.24.0-1-rosa2014.1.x86_64
lib64kf5kiowidgets5-5.24.0-1-rosa2014.1.x86_64
lib64kf5notifications5-5.24.0-1-rosa2014.1.x86_64
lib64kf5parts5-5.24.0-1-rosa2014.1.x86_64
lib64kf5bookmarks5-5.24.0-1-rosa2014.1.x86_64
lib64kf5kiofilewidgets5-5.24.0-1-rosa2014.1.x86_64
lib64kf5kdelibs4support5-5.24.0-1-rosa2014.1.x86_64
lib64kf5package5-5.24.0-1-rosa2014.1.x86_64
lib64kf5khtml5-5.24.0-1-rosa2014.1.x86_64
lib64kf5declarative5-5.24.0-1-rosa2014.1.x86_64
lib64kf5quickaddons5-5.24.0-1-rosa2014.1.x86_64
lib64kf5declarative-qml-5.24.0-1-rosa2014.1.x86_64
lib64kf5activities5-5.24.0-1-rosa2014.1.x86_64
lib64kf5waylandserver5-5.24.0-1-rosa2014.1.x86_64
lib64kf5waylandclient5-5.24.0-1-rosa2014.1.x86_64
lib64kf5activities-qml-5.24.0-1-rosa2014.1.x86_64
lib64kf5pty5-5.24.0-1-rosa2014.1.x86_64
lib64kf5coreaddons-devel-5.24.0-1-rosa2014.1.x86_64
lib64kf5auth-devel-5.24.0-1-rosa2014.1.x86_64
lib64kf5config-devel-5.24.0-1-rosa2014.1.x86_64
lib64kf5codecs-devel-5.24.0-1-rosa2014.1.x86_64
lib64kf5windowsystem-devel-5.24.0-1-rosa2014.1.x86_64
lib64kf5notifications-devel-5.24.0-1-rosa2014.1.x86_64

**Comment by F1ash** [comment]
try now: appended -std=c++11 flag.

**Comment by CMobley7** [comment]
I'm having difficulty building this as well. I used yaourt to download and build the package from the AUR. However, I get the following errors:

```
/usr/lib/libKF5Auth.so.5.34.0: undefined reference to `qt_version_tag@Qt_5.8'
/usr/lib/libKF5Auth.so.5.34.0: undefined reference to `QIODevice::isTransactionStarted() const@Qt_5'
/usr/lib/libQt5TextToSpeech.so.5: undefined reference to `QJsonObject::value(QLatin1String) const@Qt_5'
/usr/lib/libKF5Notifications.so.5.34.0: undefined reference to `QGuiApplication::desktopFileName()@Qt_5'
/usr/lib/libQt5TextToSpeech.so.5: undefined reference to `QJsonObject::contains(QLatin1String) const@Qt_5'
/usr/lib/libKF5Auth.so.5.34.0: undefined reference to `QIcon::fromTheme(QString const&)@Qt_5'
/usr/lib/libKF5ConfigCore.so.5: undefined reference to `QDateTime::QDateTime(QDateTime&&)@Qt_5'
/usr/lib/libKF5CoreAddons.so.5.34.0: undefined reference to `QtPrivate::QStringList_join(QStringList const&, QLatin1String)@Qt_5'
/usr/lib/libKF5CoreAddons.so.5.34.0: undefined reference to `QJsonValue::toString() const@Qt_5'
/usr/lib/libKF5CoreAddons.so.5.34.0: undefined reference to `QString::resize(int, QChar)@Qt_5'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/DNSCryptClient.dir/build.make:910: src/DNSCryptClient] Error 1
make[1]: *** [CMakeFiles/Makefile2:88: src/CMakeFiles/DNSCryptClient.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build dnscrypt-proxy-gui.
```

Any ideas?

**Comment by omni6** [comment]
i am on arch and tested it a minute ago, the package builds fine for me.
try installing by hand ->

```
git clone https://aur.archlinux.org/dnscrypt-proxy-gui.git
cd dnscrypt-proxy-gui
makepkg -sri

```

@F1ash could it be a dependency error?

**Comment by F1ash** [comment]
all required libs (in Fedora):
`# rpm -qR dnscrypt-proxy-gui`
/bin/sh
dnscrypt-proxy
hicolor-icon-theme
kf5-kauth
kf5-knotifications
libKF5Auth.so.5()(64bit)
libKF5CoreAddons.so.5()(64bit)
libKF5Notifications.so.5()(64bit)
libQt5Core.so.5()(64bit)
libQt5Core.so.5(Qt_5)(64bit)
libQt5Core.so.5(Qt_5.9)(64bit)
libQt5DBus.so.5()(64bit)
libQt5DBus.so.5(Qt_5)(64bit)
libQt5DBus.so.5(Qt_5_PRIVATE_API)(64bit)
libQt5Gui.so.5()(64bit)
libQt5Gui.so.5(Qt_5)(64bit)
libQt5Widgets.so.5()(64bit)
libQt5Widgets.so.5(Qt_5)(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.17)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libm.so.6()(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
polkit
qt5-qtbase
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
rtld(GNU_HASH)
systemd

**Comment by CMobley7** [comment]
@omni6 @F1ash, it appears to be user error on my part. Conflicting versions of software. It works perfectly now. Thank you for your hard work.
