### ISSUE TITLE
[INVALID] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [F1ash/dnscrypt-proxy-gui#6]
Dear @F1ash,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by F1ash** [comment]
Unfortunately this is not possible, because application uses systemd, polkit, d-bus and works with UNIX filesystem.
For it need to port those services to Win and rewrite some code.

**Comment by sergeevabc** [comment]
Thank you for letting me know, @F1ash.
