### ISSUE TITLE
dnscrypt-proxy2

### ISSUE THREAD

**Issue by omni6** [F1ash/dnscrypt-proxy-gui#9]
as you may heard already the maintainer of the original nscrypt-proxy has quit.  Here's the rewrite in go, dont know what it means for this project....

https://github.com/jedisct1/dnscrypt-proxy

**Comment by F1ash** [comment]
i think that it will be not to broke the app, because gui works with dnscrypt-proxy systemd service through dbus... maybe new version will add new capabilities...

**Comment by omni6** [comment]
the config file has another format and is now found at /etc/dnscrypt-proxy/dnscrypt-proxy.toml but yes i think it should be possible to adopt...
The executable has not these options the old version had. 
```
/ » dnscrypt-proxy -h
Usage of dnscrypt-proxy:
  -config string
        path to the configuration file (default "/etc/dnscrypt-proxy/dnscrypt-proxy.toml")
  -loglevel value
        Log level (0-6) (default 2)

```

**Comment by omni6** [comment]
Are you watching the new dnscrypt-proxy progress? Any chances to adapt the changes?

**Comment by F1ash** [comment]
dnscrypt-proxy-2* is absent in Fedora yet then any progress yet...

**Comment by omni6** [comment]
fedora is reaaaally slooooow

**Comment by jedisct1** [comment]
There is https://copr.fedorainfracloud.org/coprs/eclipseo/dnscrypt-proxy/

**Comment by F1ash** [comment]
dnscrypt-proxy-2 is available in Fedora repo now, then i will try implement app with new service. As will have a time...

**Comment by omni6** [comment]
Nice man!

**Comment by F1ash** [comment]
Try to use with dnscrypt-proxy v.2 . But testing the servers respond not implemented yet.

**Comment by F1ash** [comment]
Testing is implemented (for IPv4)... Need some improvements...
